apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  template:   
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodes-hello
        image: arunimadas18/node-hello:latest
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: 100m        
            memory: 128Mi    
          limits:
            cpu: 200m        
            memory: 256Mi