# Stage 1
FROM node:latest AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

# Stage 2
FROM node:alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY . .
EXPOSE 4000
CMD ["node", "hello.js"]
